AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  smart-garage-notifications

  Sample SAM Template for smart-garage-notifications

Parameters:
  ENVIRONMENT:
    Type: String
    Default: PreProduction
    AllowedValues:
      - PreProduction
      - Production
    Description: The stages based on CI/CD Pipeline in CodePipeline

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SmartGarageNotification:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub SmartGarageNotificationApi-${ENVIRONMENT}
      StageName: !Sub ${ENVIRONMENT}
      Auth:
        ApiKeyRequired: True
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: SmartGarageNotificationApiUsagePlan
          Quota:
            Limit: 50
            Period: DAY
          Throttle:
            BurstLimit: 1
            RateLimit: 1

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref SmartGarageNotification

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${SmartGarageNotification}.execute-api.${AWS::Region}.amazonaws.com/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  # HelloWorldFunctionIamRole:
  #   Description: "Implicit IAM Role created for Hello World function"
  #   Value: !GetAtt HelloWorldFunctionRole.Arn
